[package]
name = "xeno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apple-dmg = "0.1.0"
squashfs-ng = "0.1.2"
